package dev.ebnbin.android.core

import androidx.annotation.ColorRes
import androidx.annotation.StyleRes

enum class MaterialColor(
    val id: String,
    val isFull: Boolean,
    @ColorRes val lightColorId: Int,
    @ColorRes val darkColorId: Int,
    @StyleRes val dayNightThemeId: Int,
) {
    PINK_FULL(
        id = "pink_full",
        isFull = true,
        lightColorId = R.color.material_pink_full_50,
        darkColorId = R.color.material_pink_full_70,
        dayNightThemeId = R.style.MaterialTheme_Pink_Full_DayNight,
    ),
    RED_FULL(
        id = "red_full",
        isFull = true,
        lightColorId = R.color.material_red_full_50,
        darkColorId = R.color.material_red_full_70,
        dayNightThemeId = R.style.MaterialTheme_Red_Full_DayNight,
    ),
    ORANGE_FULL(
        id = "orange_full",
        isFull = true,
        lightColorId = R.color.material_orange_full_50,
        darkColorId = R.color.material_orange_full_70,
        dayNightThemeId = R.style.MaterialTheme_Orange_Full_DayNight,
    ),
    AMBER_FULL(
        id = "amber_full",
        isFull = true,
        lightColorId = R.color.material_amber_full_50,
        darkColorId = R.color.material_amber_full_70,
        dayNightThemeId = R.style.MaterialTheme_Amber_Full_DayNight,
    ),
    LIME_FULL(
        id = "lime_full",
        isFull = true,
        lightColorId = R.color.material_lime_full_50,
        darkColorId = R.color.material_lime_full_70,
        dayNightThemeId = R.style.MaterialTheme_Lime_Full_DayNight,
    ),
    GREEN_FULL(
        id = "green_full",
        isFull = true,
        lightColorId = R.color.material_green_full_50,
        darkColorId = R.color.material_green_full_70,
        dayNightThemeId = R.style.MaterialTheme_Green_Full_DayNight,
    ),
    TEAL_FULL(
        id = "teal_full",
        isFull = true,
        lightColorId = R.color.material_teal_full_50,
        darkColorId = R.color.material_teal_full_70,
        dayNightThemeId = R.style.MaterialTheme_Teal_Full_DayNight,
    ),
    CYAN_FULL(
        id = "cyan_full",
        isFull = true,
        lightColorId = R.color.material_cyan_full_50,
        darkColorId = R.color.material_cyan_full_70,
        dayNightThemeId = R.style.MaterialTheme_Cyan_Full_DayNight,
    ),
    LIGHT_BLUE_FULL(
        id = "light_blue_full",
        isFull = true,
        lightColorId = R.color.material_light_blue_full_50,
        darkColorId = R.color.material_light_blue_full_70,
        dayNightThemeId = R.style.MaterialTheme_LightBlue_Full_DayNight,
    ),
    INDIGO_FULL(
        id = "indigo_full",
        isFull = true,
        lightColorId = R.color.material_indigo_full_50,
        darkColorId = R.color.material_indigo_full_70,
        dayNightThemeId = R.style.MaterialTheme_Indigo_Full_DayNight,
    ),
    DEEP_PURPLE_FULL(
        id = "deep_purple_full",
        isFull = true,
        lightColorId = R.color.material_deep_purple_full_50,
        darkColorId = R.color.material_deep_purple_full_70,
        dayNightThemeId = R.style.MaterialTheme_DeepPurple_Full_DayNight,
    ),
    PURPLE_FULL(
        id = "purple_full",
        isFull = true,
        lightColorId = R.color.material_purple_full_50,
        darkColorId = R.color.material_purple_full_70,
        dayNightThemeId = R.style.MaterialTheme_Purple_Full_DayNight,
    ),
    PINK_HALF(
        id = "pink_half",
        isFull = false,
        lightColorId = R.color.material_pink_half_50,
        darkColorId = R.color.material_pink_half_70,
        dayNightThemeId = R.style.MaterialTheme_Pink_Half_DayNight,
    ),
    RED_HALF(
        id = "red_half",
        isFull = false,
        lightColorId = R.color.material_red_half_50,
        darkColorId = R.color.material_red_half_70,
        dayNightThemeId = R.style.MaterialTheme_Red_Half_DayNight,
    ),
    ORANGE_HALF(
        id = "orange_half",
        isFull = false,
        lightColorId = R.color.material_orange_half_50,
        darkColorId = R.color.material_orange_half_70,
        dayNightThemeId = R.style.MaterialTheme_Orange_Half_DayNight,
    ),
    AMBER_HALF(
        id = "amber_half",
        isFull = false,
        lightColorId = R.color.material_amber_half_50,
        darkColorId = R.color.material_amber_half_70,
        dayNightThemeId = R.style.MaterialTheme_Amber_Half_DayNight,
    ),
    LIME_HALF(
        id = "lime_half",
        isFull = false,
        lightColorId = R.color.material_lime_half_50,
        darkColorId = R.color.material_lime_half_70,
        dayNightThemeId = R.style.MaterialTheme_Lime_Half_DayNight,
    ),
    GREEN_HALF(
        id = "green_half",
        isFull = false,
        lightColorId = R.color.material_green_half_50,
        darkColorId = R.color.material_green_half_70,
        dayNightThemeId = R.style.MaterialTheme_Green_Half_DayNight,
    ),
    TEAL_HALF(
        id = "teal_half",
        isFull = false,
        lightColorId = R.color.material_teal_half_50,
        darkColorId = R.color.material_teal_half_70,
        dayNightThemeId = R.style.MaterialTheme_Teal_Half_DayNight,
    ),
    CYAN_HALF(
        id = "cyan_half",
        isFull = false,
        lightColorId = R.color.material_cyan_half_50,
        darkColorId = R.color.material_cyan_half_70,
        dayNightThemeId = R.style.MaterialTheme_Cyan_Half_DayNight,
    ),
    LIGHT_BLUE_HALF(
        id = "light_blue_half",
        isFull = false,
        lightColorId = R.color.material_light_blue_half_50,
        darkColorId = R.color.material_light_blue_half_70,
        dayNightThemeId = R.style.MaterialTheme_LightBlue_Half_DayNight,
    ),
    INDIGO_HALF(
        id = "indigo_half",
        isFull = false,
        lightColorId = R.color.material_indigo_half_50,
        darkColorId = R.color.material_indigo_half_70,
        dayNightThemeId = R.style.MaterialTheme_Indigo_Half_DayNight,
    ),
    DEEP_PURPLE_HALF(
        id = "deep_purple_half",
        isFull = false,
        lightColorId = R.color.material_deep_purple_half_50,
        darkColorId = R.color.material_deep_purple_half_70,
        dayNightThemeId = R.style.MaterialTheme_DeepPurple_Half_DayNight,
    ),
    PURPLE_HALF(
        id = "purple_half",
        isFull = false,
        lightColorId = R.color.material_purple_half_50,
        darkColorId = R.color.material_purple_half_70,
        dayNightThemeId = R.style.MaterialTheme_Purple_Half_DayNight,
    ),
    ;
}
